### ISSUE TITLE
Support for old node version

### ISSUE THREAD

**Issue by morawskim** [epistemex/mdncomp#5]
Hello,

When I call
```
mdncomp html*toblob
```
I get error
```
TypeError: (n + "").padStart is not a function
    at n.forEach (/run/user/1000/cdtmp-bMKeXZ/node_modules/mdncomp/build/build.min.js:6:8657)
    at Array.forEach (native)
    at Command.go (/run/user/1000/cdtmp-bMKeXZ/node_modules/mdncomp/build/build.min.js:6:8599)
    at Command.listener (/run/user/1000/cdtmp-bMKeXZ/node_modules/commander/index.js:315:8)
    at emitOne (events.js:96:13)
    at Command.emit (events.js:188:7)
    at Command.parseArgs (/run/user/1000/cdtmp-bMKeXZ/node_modules/commander/index.js:653:12)
    at Command.parse (/run/user/1000/cdtmp-bMKeXZ/node_modules/commander/index.js:474:21)
    at init (/run/user/1000/cdtmp-bMKeXZ/node_modules/mdncomp/build/build.min.js:6:6107)
    at Object.<anonymous> (/run/user/1000/cdtmp-bMKeXZ/node_modules/mdncomp/bin/mdncomp.js:21:35)
```
This looks like the String.padStart require node8 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart).
On the same website there is a polyfill. I copy this code and paste in `bin/mdncomp.js` for test.
After this I can run mdncomp on node v6.11.1
```
mdncomp html*toblob
[0] api.HTMLCanvasElement.toBlob
[1] api.HTMLCanvasElement.toBlob.Image_quality
```

**Comment by epistemex** [comment]
Adding these (`padStart`/`padEnd`/`includes`) as polyfills for the next release scheduled for later today.

**Comment by epistemex** [comment]
Updated and published. Thanks @morawskim for reporting.

**Comment by epistemex** [comment]
Needed to bump to version 1.13.3-alpha (published).
